export const CHROME_CONSTANTS = {
  CHROME_OPTIONS1: [
    "----user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "--disable-blink-features=AutomationControlled",
    "--use-fake-ui-for-media-stream",
    "--window-size=1920,1080",
    "--disable-notifications",
    "--auto-select-desktop-capture-source=[RECORD]",
    "--enable-usermedia-screen-capturing",
    "--allow-running-insecure-content",
    "--safebrowsing-disable-download-protection",
    "--disable-download-notification",
    "--disable-gpu",
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    "--disable-software-rasterizer",
    "--remote-debugging-port=9222",
    "--headless",
  ],
  CHROME_OPTIONS: [
    "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36",
    "--disable-blink-features=AutomationControlled",
    "--use-fake-ui-for-media-stream",
    "--window-size=1920,1080",
    "--disable-notifications",
    "--auto-select-desktop-capture-source=[RECORD]",
    "--enable-usermedia-screen-capturing",
    "--allow-running-insecure-content",
    "--safebrowsing-disable-download-protection",
    "--disable-download-notification",
    "--disable-gpu",
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--disable-extensions",
    "--disable-software-rasterizer",
    "--remote-debugging-port=9222",
    // "--headless",
    "--force-device-scale-factor=1",
    "--high-dpi-support=1",
    "--disable-low-res-tiling",
    "--enable-font-antialiasing",
    "--enable-smooth-scrolling",
    "--disable-pinch",
    "--no-first-run",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--user-data-dir=/path/to/your/chrome-profile",
  ],
  MEDIA_STREAM_OPTIONS: {
    video: {
      displaySurface: "browser",
    },
    systemAudio: "include",
    audio: true,
    preferCurrentTab: true,
  },
};
